# Generated by Django 5.0.1 on 2024-01-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="File name"
                    ),
                ),
                ("file", models.FileField(upload_to="post_files/")),
                (
                    "code",
                    models.IntegerField(
                        default=0, unique=True, verbose_name="File code"
                    ),
                ),
                (
                    "download_count",
                    models.IntegerField(default=0, verbose_name="Downloaded"),
                ),
            ],
            options={
                "verbose_name": "Post file",
                "verbose_name_plural": "Post files",
            },
        ),
    ]
